Repository clairBuoyant/web, pull requests merged in 2022-07, with the labels that each got.

#2 chore: update Dockerfile and reorg folder structure
  .dockerignore
  Dockerfile
  package.json
  src/App.test.tsx
  src/app.tsx
  src/constants/index.ts
  src/index.tsx
  src/layouts/.gitkeep
  src/pages/.gitkeep
  src/types/.gitkeep
  yarn.lock
Labels: dependencies, devOps

#8 feat(world-map): create and render component
  package.json
  public/index.html
  src/app.test.tsx
  src/app.tsx
  src/components/.gitkeep
  src/components/world-map/index.ts
  src/components/world-map/world-map.css
  src/components/world-map/world-map.tsx
  src/constants/index.ts
  src/types/.gitkeep
  src/types/buoy.type.ts
  src/types/index.ts
  yarn.lock
Labels: dependencies, enhancement

#14 fix(world-map): missing buoy data when infinitely scrolling
  src/components/world-map/world-map.tsx
Labels: bug

#17 feat: Navbar creation
  package-lock.json
  package.json
  src/app.tsx
  src/components/navbar/index.ts
  src/components/navbar/navbar.constants.ts
  src/components/navbar/navbar.css
  src/components/navbar/navbar.tsx
  yarn.lock
Labels: dependencies, enhancement
